# Site settings
title: ¿Hay Acuerdo?
email: prensa@ciudadanointeligente.org
description: La Reforma Educacional nos importa a todos. Infórmate sobre los puntos de vista de diversos actores sociales con respecto a las posturas del Gobierno. Elige un actor y compara sus posiciones.
baseurl: http://ciudadanointeligente.github.io/hayacuerdos-fci/
# url: http://localhost:4000	#Development mode
analytics: "UA-41822715-4"

# Educacion
gsheeteducacion: "https://docs.google.com/spreadsheets/d/1j7XjeGe4OJ8vYtDwx_ipOvR0z5gsafVnh9b37-CJ58A/pubhtml"
#First page to load
gsheeteducacion-sheetpage: "gobierno-fech"

# Binominal
gsheetbinominal: "https://docs.google.com/spreadsheets/d/1dxarZUl5bsHAe-DhGIC6ox5_JD6oVvqmkNrOObrz3Rw/pubhtml"
#First page to load
gsheetbinominal-sheetpage: "gobierno-evopoli"




#twitter
twitter:
  username: '@ciudadanoi'

# Build settings
markdown: kramdown
permalink: pretty

gems:
- jekyll-compass
