# site settings
title: ¿Hay acuerdo?
email: contacto@tuorganizacion.org
description: Infórmate sobre los los puntos de vista de diversos actores sociales con respecto a la reforma del sistema binominal. Elige dos y compara sus posiciones.
baseurl: http://hayacuerdo.tuorganizacion.org/
basedomain: hayacuerdo.tuorganizacion.org
analytics: "UA-12345678-X"

#twitter
twitter:
  username: '@ciudadanoi'

# build settings
markdown: kramdown
permalink: pretty

gems:
- jekyll-compass
